name: Post Daily News to Slack

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-daily-post:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade openai slack_sdk feedparser beautifulsoup4 requests

      - name: Run post_daily_news.py
        run: python post_daily_news.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
