name: Send Alzheimer News to Slack

on:
  workflow_dispatch:   # 手動実行
  schedule:
    - cron: '0 23 * * *'  # 毎日23時UTC（JST朝8時）

permissions:
  contents: read

jobs:
  send-to-slack:
    runs-on: ubuntu-latest

    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade openai slack_sdk feedparser beautifulsoup4 requests

      - name: Run Slack post script
        run: python send_to_slack.py
